export enum PermissionsEnum {
  // Brands
  BRANDS_CREATE = 'BRANDS_CREATE',
  BRANDS_READ = 'BRANDS_READ',
  BRANDS_UPDATE = 'BRANDS_UPDATE',
  BRANDS_DELETE = 'BRANDS_DELETE',

  // Categories
  CATEGORIES_CREATE = 'CATEGORIES_CREATE',
  CATEGORIES_READ = 'CATEGORIES_READ',
  CATEGORIES_UPDATE = 'CATEGORIES_UPDATE',
  CATEGORIES_DELETE = 'CATEGORIES_DELETE',

  // Education Levels
  EDUCATION_LEVELS_CREATE = 'EDUCATION_LEVELS_CREATE',
  EDUCATION_LEVELS_READ = 'EDUCATION_LEVELS_READ',
  EDUCATION_LEVELS_UPDATE = 'EDUCATION_LEVELS_UPDATE',
  EDUCATION_LEVELS_DELETE = 'EDUCATION_LEVELS_DELETE',

  // Products
  PRODUCTS_CREATE = 'PRODUCTS_CREATE',
  PRODUCTS_READ = 'PRODUCTS_READ',
  PRODUCTS_UPDATE = 'PRODUCTS_UPDATE',
  PRODUCTS_DELETE = 'PRODUCTS_DELETE',

  // Product Groups
  PRODUCT_GROUPS_CREATE = 'PRODUCT_GROUPS_CREATE',
  PRODUCT_GROUPS_READ = 'PRODUCT_GROUPS_READ',
  PRODUCT_GROUPS_UPDATE = 'PRODUCT_GROUPS_UPDATE',
  PRODUCT_GROUPS_DELETE = 'PRODUCT_GROUPS_DELETE',

  // Sizes
  SIZES_CREATE = 'SIZES_CREATE',
  SIZES_READ = 'SIZES_READ',
  SIZES_UPDATE = 'SIZES_UPDATE',
  SIZES_DELETE = 'SIZES_DELETE',

  // Target Audiences
  TARGET_AUDIENCES_CREATE = 'TARGET_AUDIENCES_CREATE',
  TARGET_AUDIENCES_READ = 'TARGET_AUDIENCES_READ',
  TARGET_AUDIENCES_UPDATE = 'TARGET_AUDIENCES_UPDATE',
  TARGET_AUDIENCES_DELETE = 'TARGET_AUDIENCES_DELETE',

  // Users
  USERS_CREATE = 'USERS_CREATE',
  USERS_READ = 'USERS_READ',
  USERS_UPDATE = 'USERS_UPDATE',
  USERS_DELETE = 'USERS_DELETE',

  // Permissions
  PERMISSIONS_CREATE = 'PERMISSIONS_CREATE',
  PERMISSIONS_READ = 'PERMISSIONS_READ',
  PERMISSIONS_UPDATE = 'PERMISSIONS_UPDATE',
  PERMISSIONS_DELETE = 'PERMISSIONS_DELETE',

  // AWS S3 (files)
  // AWS_S3_UPLOAD = 'AWS_S3_UPLOAD',
  FILES_CREATE = 'FILES_CREATE',
  FILES_READ = 'FILES_READ',
  FILES_UPDATE = 'FILES_UPDATE',
  FILES_DELETE = 'FILES_DELETE',
}
